# Generated by Django 5.1 on 2024-08-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('soil_moisture_level', models.FloatField()),
                ('temperature', models.FloatField()),
                ('ph_level', models.FloatField()),
                ('uv_intensity', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('water_pressure', models.FloatField()),
                ('tank_water_volume', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Field Data',
            },
        ),
        migrations.DeleteModel(
            name='PHLevel',
        ),
        migrations.DeleteModel(
            name='Rainfall',
        ),
        migrations.DeleteModel(
            name='SoilMoistureLevel',
        ),
        migrations.DeleteModel(
            name='TankWaterVolume',
        ),
        migrations.DeleteModel(
            name='Temperature',
        ),
        migrations.DeleteModel(
            name='UVIntensity',
        ),
        migrations.DeleteModel(
            name='WaterPressure',
        ),
    ]
