# Generated by Django 5.1 on 2024-08-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('working', 'Working'), ('not_working', 'Not Working'), ('issue_detected', 'Issue Detected')], default='not_working', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
